routes/web.php
<?php

use App\Http\Controllers\front\NoticiaController as FrontNoticiaController;
use App\Http\Controllers\back\NoticiaController as BackNoticiaController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

// Pagina de inicio frontend
// Quiero listar todas las noticias con solo algunos campos y cuand pinche en la noticia me muestre la noticia completa
Route::controller(FrontNoticiaController::class)->group(function () {
    Route::get('/', 'index')->name('home');
    Route::get('/front/noticias/{noticia}', 'show')->name('front.noticias.show');
});

// Los usuarios registrados pueden hacer esto
Route::middleware('auth')->group(function () {
    // Pagina de inicio backend
    // Si pulso sobre el icono del menu me lleve al front
    // Quiero ver informacion del usuario y un menu con gestion de noticias | Crear Noticias | Noticias del usuario |
    // Dropdown para cerrar sesion (perfil, cerrar sesion)
    Route::get('/back/index', function () {
        return view('back.index');
    })->name('back.index');

    // Gestion del perfil
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    // Noticias
    // Route::controller(BackNoticiaController::class)->group(function () {
    //     // Para mostrar las noticias del usuario lougeado
    //     Route::get('/back/noticias/listado', 'listado')->name('back.noticias.listado');
    Route::resource('back/noticias', BackNoticiaController::class)->names('back.noticias');
Route::get('back/noticias/listado', [BackNoticiaController::class, 'listado'])->name('back.noticias.listado');
   //Route::resource('back/noticias', BackNoticiaController::class)->names('back.noticias.listado');
    });

 

require __DIR__.'/auth.php';

app/Http/Controllers/front/NoticiaController.php
<?php

namespace App\Http\Controllers\front;

use App\Http\Controllers\Controller;
use App\Models\Noticia;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class NoticiaController extends Controller {
    /**
     * Debe mostrar todas las noticias en frontend. No debe aparecer los botones de edicion.
    */
    public function index() {
        // Obtengo todas las noticias

        // Quiero ver el nombre del usuario que ha creado la noticia
        $noticias = Noticia::all();


        // Redireciona a la vista front.index frontend
        return view('front.index', compact('noticias'));
    }

    public function show(Noticia $noticia) {
        return view('front.noticias.show', compact('noticia'));
    }
}

app/View/Components/MainLayout.php
<?php

namespace App\View\Components;

use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

/**
 * Este componenente es el layout para las vistas del frontend
*/
class MainLayout extends Component {
    /**
     * Create a new component instance.
     */
    public function __construct() {
        //
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string {
        return view('layouts.main');
    }
}

resources/views/front/index.blade.php
<x-main-layout>
    @foreach ($noticias as $noticia)
        <a href="{{ route('front.noticias.show', $noticia) }}" class="container mx-auto">
            <div class="max-w-6xl mx-auto bg-white border border-gray-300 rounded-lg shadow-md hover:shadow-lg transition duration-300 ease-in-out hover:border-gray-400 hover:bg-gray-50 relative">
                <div class="absolute top-0 right-0 p-2 bg-gray-200 bg-opacity-75 rounded-md border border-gray-300">
                    <p class="text-xs text-gray-700">{{ $noticia->created_at->diffForHumans() }}</p>
                </div>
                <div class="flex items-center">
                    <div class="w-full md:w-1/3 overflow-hidden">
                        <img class="rounded-l-lg md:rounded-l-none md:rounded-r-none w-full h-auto" src="{{ asset('storage/fotos/koala.jpg') }}" alt="Imagen de la noticia" />
                    </div>
                    <div class="w-full md:w-2/3 p-6">
                        <div class="flex items-center justify-between">
                            <h2 class="text-2xl font-semibold leading-7 text-gray-900">{{ $noticia->titulo }}</h2>
                        </div>
                        <p class="mt-3 text-base leading-6 text-gray-700">{{ Str::limit($noticia->contenido, 150, '...') }}</p>
                        <div class="mt-4 text-sm text-gray-600 flex items-center justify-between">
                            <div>
                                <svg class="h-4 w-4 mr-1.5 text-gray-400 inline-block" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 14l9-5-9-5-9 5 9 5z"></path>
                                </svg>
                                <p class="inline-block">Autor: {{ $noticia->user->name }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </a>
    @endforeach
</x-main-layout>