routes/web.php
<?php

use App\Http\Controllers\front\NoticiaController as FrontNoticiaController;
use App\Http\Controllers\back\NoticiaController as BackNoticiaController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

// Pagina de inicio frontend
// Quiero listar todas las noticias con solo algunos campos y cuand pinche en la noticia me muestre la noticia completa
Route::controller(FrontNoticiaController::class)->group(function () {
    Route::get('/', 'index')->name('home');
    Route::get('/front/noticias/{noticia}', 'show')->name('front.noticias.show');
});

// Los usuarios registrados pueden hacer esto
Route::middleware('auth')->group(function () {
    // Pagina de inicio backend
    // Si pulso sobre el icono del menu me lleve al front
    // Quiero ver informacion del usuario y un menu con gestion de noticias | Crear Noticias | Noticias del usuario |
    // Dropdown para cerrar sesion (perfil, cerrar sesion)
    Route::get('/back/index', function () {
        return view('back.index');
    })->name('back.index');

    // Gestion del perfil
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    // Noticias
    // Route::controller(BackNoticiaController::class)->group(function () {
    //     // Para mostrar las noticias del usuario lougeado
    //     Route::get('/back/noticias/listado', 'listado')->name('back.noticias.listado');
    Route::resource('back/noticias', BackNoticiaController::class)->names('back.noticias');
Route::get('back/noticias/listado', [BackNoticiaController::class, 'listado'])->name('back.noticias.listado');
   //Route::resource('back/noticias', BackNoticiaController::class)->names('back.noticias.listado');
    });

 

require __DIR__.'/auth.php';

app/Models/Noticia.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Facades\Schema;

class Noticia extends Model {
    use HasFactory;

    // protected $table = 'noticias';

    protected $fillable = [
        'titulo',
        'contenido',
        'foto',
        'user_id',
    ];

    public static $labels = [
        'titulo' => 'Título',
        'contenido' => 'Contenido',
        'foto' => 'Foto',
        'user_id' => 'Usuario',
        // 'nombreuser' => 'Nombre',
    ];

    /**
     ** Recupera la lista de campos de la tabla asociada al modelo.
     *
     * @return array La lista de nombres de campos.
    */
    public function getFields(): array {
        return Schema::getColumnListing($this->table);
    }

    /**
     ** Recupera la etiqueta de un atributo dado.
     *
     * @param string $attribute El nombre del atributo.
     * @return string La etiqueta del atributo, o el nombre del atributo si no se encuentra una etiqueta.
    */
    public function getAttributeLabel($attribute): string {
        return self::$labels[$attribute] ?? $attribute;
    }

    public function user() : BelongsTo {
        return $this->belongsTo(User::class);
    }

    public function getNombreuserAttribute(): string {
        return $this->user->name;
    }
}

app/Http/Controllers/back/NoticiaController.php
<?php

namespace App\Http\Controllers\back;

use App\Http\Controllers\Controller;
use App\Http\Requests\NoticiaStoreRequest;
use App\Http\Requests\NoticiaUpdateRequest;
use App\Models\Noticia;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class NoticiaController extends Controller {
    /**
     * Display a listing of the resource.
     */
    public function index() {
        $noticias = Noticia::all();
        return view('back.noticias.index', compact('noticias'));
    }

    /**
     * Show the form for creating a new resource.
    */
    public function create() {
        return view('back.noticias.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(NoticiaStoreRequest $request) {
        $fotoEnviada = $request->file('foto');

        if ($fotoEnviada) {
            $foto = $fotoEnviada->store('fotos', 'public');
        } else {
            $foto = null;
        }

         $noticia = new Noticia();
        $noticia->fill($request->validated()); // Usar datos validados
        $noticia->foto = $foto;
        $noticia->user_id = Auth::id(); // Asignar el ID del usuario autenticado
        $noticia->save();

        return redirect()
            ->route('back.noticias.listado')
            ->with('mensaje', 'Noticia se ha creado con éxito');
    }

    /**
     * Display the specified resource.
     */
    public function show(Noticia $noticia) {
        return view('back.noticias.show', compact('noticia'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Noticia $noticia) {
        return view('back.noticias.edit', compact('noticia'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(NoticiaUpdateRequest $request, Noticia $noticia) {
        if ($request->hasFile('foto')) {
            $fotoEnviada = $request->file('foto');
            Storage::disk('public')->delete($noticia->foto);

            $nuevaFoto = $fotoEnviada->store('fotos', 'public');
            $noticia->fill($request->validated());
            $noticia->foto = $nuevaFoto;
        } else {
            $noticia->fill($request->validated());
        }

        $noticia->save();

        return redirect()
            ->route('back.noticias.listado')
            ->with('mensaje', 'Noticia actualizada con éxito');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Noticia $noticia) {
        Storage::disk('public')->delete($noticia->foto);
        $noticia->delete();

        return redirect()
            ->route('back.noticias.listado')
            ->with('mensaje', 'Noticia borrada con éxito');
    }

    public function listado() {
        $noticias = Noticia::where('user_id', Auth::id())->get();
        return view('back.noticias.listado', compact('noticias'));
    }
}

app/Http/Controllers/front/NoticiaController.php
<?php

namespace App\Http\Controllers\front;

use App\Http\Controllers\Controller;
use App\Models\Noticia;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class NoticiaController extends Controller {
    /**
     * Debe mostrar todas las noticias en frontend. No debe aparecer los botones de edicion.
    */
    public function index() {
        // Obtengo todas las noticias

        // Quiero ver el nombre del usuario que ha creado la noticia
        $noticias = Noticia::all();


        // Redireciona a la vista front.index frontend
        return view('front.index', compact('noticias'));
    }

    public function show(Noticia $noticia) {
        return view('front.noticias.show', compact('noticia'));
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

/**
 * Este componente es el layout para las vistas del backend
 */
class AppLayout extends Component {
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View {
        return view('layouts.app');
    }
}

resources/views/back/noticias/create.blade.php
<x-app-layout>
    <div class="container mx-auto p-6 mt-5 bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
        <form action="{{ route('back.noticias.store') }}" method="POST" enctype="multipart/form-data">
            @csrf

            <div class="space-y-12">
                <div class="border-b border-gray-900/10 pb-12">
                    <h2 class="text-base font-semibold leading-7 text-gray-900">Noticias</h2>
                    <p class="mt-1 text-sm leading-6 text-gray-600">Crear una noticia y lo verá todo el mundo.</p>

                    <input type="hidden" name="user_id" value="{{ Auth::user()->id }}">

                    <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
                        <div class="sm:col-span-4">
                            <label for="titulo" class="block text-sm font-medium leading-6 text-gray-900">Título</label>
                            <div class="mt-2">
                                <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
                                    <input type="text" name="titulo" id="titulo" placeholder="Título" class="block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6">
                                </div>
                                @error('titulo')
                                    <p class="text-red-500"> {{ $message }} </p>
                                @enderror
                            </div>
                        </div>

                        <div class="col-span-full">
                            <label for="contenido" class="block text-sm font-medium leading-6 text-gray-900">Contenido</label>
                            <div class="mt-2">
                                <textarea id="contenido" name="contenido" rows="3" placeholder="Pon el contenido de la noticia" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"></textarea>
                            </div>
                            <p class="mt-3 text-sm leading-6 text-gray-600">Escribe la noticia</p>
                        </div>
                    </div>

                    <div class="col-span-full mt-7">
                        <label for="cover-photo" class="block text-sm font-medium leading-6 text-gray-900">Cover photo</label>
                        <div class="mt-2 flex justify-center rounded-lg border border-dashed border-gray-900/25 px-6 py-10">
                            <div class="text-center">
                                <div id="preview" class="bg-cover">
                                    <svg id="svg-icon" class="mx-auto h-12 w-12 text-gray-300" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
                                        <path fill-rule="evenodd" d="M1.5 6a2.25 2.25 0 012.25-2.25h16.5A2.25 2.25 0 0122.5 6v12a2.25 2.25 0 01-2.25 2.25H3.75A2.25 2.25 0 011.5 18V6zM3 16.06V18c0 .414.336.75.75.75h16.5A.75.75 0 0021 18v-1.94l-2.69-2.689a1.5 1.5 0 00-2.12 0l-.88.879.97.97a.75.75 0 11-1.06 1.06l-5.16-5.159a1.5 1.5 0 00-2.12 0L3 16.061zm10.125-7.81a1.125 1.125 0 112.25 0 1.125 1.125 0 01-2.25 0z" clip-rule="evenodd" />
                                    </svg>
                                </div>
                                <div class="mt-4 flex text-sm leading-6 text-gray-600">
                                    <label for="foto" class="relative cursor-pointer rounded-md bg-white font-semibold text-indigo-600 focus-within:outline-none focus-within:ring-2 focus-within:ring-indigo-600 focus-within:ring-offset-2 hover:text-indigo-500">
                                        <div class="flex flex-col items-center justify-center">
                                            <span>Subir Imagen</span>
                                            <p class="text-xs leading-5 text-gray-600">PNG, JPG, hasta 1MB</p>
                                        </div>
                                        <input type="file" id="foto" name="foto" class="sr-only">
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="mt-6 flex justify-center gap-x-6">
                    <button type="submit" class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Guardar</button>
                </div>
            </div>
        </form>
    </div>
</x-app-layout>

<script>
    document.getElementById('foto').addEventListener('change', function(e) {
        var file = e.target.files[0];
        var reader = new FileReader();
        var preview = document.getElementById('preview');
        var svgIcon = document.getElementById('svg-icon');

        reader.onloadend = function() {
            preview.style.backgroundImage = 'url("' + reader.result + '")';
            preview.style.backgroundSize = 'contain';
            preview.style.backgroundRepeat = 'no-repeat';
            preview.style.backgroundPosition = 'center';
            preview.classList.add('w-64', 'h-64');
            svgIcon.style.display = 'none';
        }

        if (file) {
            reader.readAsDataURL(file);
        } else {
            preview.style.backgroundImage = 'none';
            preview.classList.remove('w-64', 'h-64');
            svgIcon.style.display = 'block';
        }
    });
</script>

resources/views/back/noticias/edit.blade.php
<x-app-layout >
    <div class="container mx-auto p-6 mt-5 bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
        <form action="{{ route('back.noticias.update', $noticia) }}" method="POST"  enctype="multipart/form-data">
            @csrf
            @method('PUT')

            <div class="space-y-12">
                <div class="border-b border-gray-900/10 pb-12">
                    <h2 class="text-base font-semibold leading-7 text-gray-900">Noticias</h2>
                    <p class="mt-1 text-sm leading-6 text-gray-600">Crear una noticia y lo vera todo el mundo.</p>

                    <input type="hidden" name="user_id" value="{{ Auth::user()->id }}">

                    <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
                        <div class="sm:col-span-4">
                            <label for="titulo" class="block text-sm font-medium leading-6 text-gray-900">Titulo</label>

                            <div class="mt-2">
                                <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
                                    <input type="text" name="titulo" id="titulo" value="{{ old('titulo', $noticia->titulo) }}" class="block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6">
                                    @error('titulo')
                                        <p style="color: #dc3545;"> {{ $message }} </p>
                                    @enderror
                                </div>
                            </div>
                        </div>

                        <div class="col-span-full">
                            <label for="contenido" class="block text-sm font-medium leading-6 text-gray-900">Contenido</label>
                            <div class="mt-2">
                                <textarea id="contenido" name="contenido" rows="3" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">{{ old('contenido', $noticia->contenido) }}</textarea>
                            </div>

                            <p class="mt-3 text-sm leading-6 text-gray-600">Escribe la noticia</p>
                        </div>
                    </div>

                    <div class="col-span-full gap-y-8 mt-7">
                        <label for="cover-photo" class="block text-sm font-medium leading-6 text-gray-900">Cover photo</label>
                        <div class="mt-2 flex justify-center rounded-lg border border-dashed border-gray-900/25 px-6 py-10">
                            <div class="text-center">
                                <div id="preview" class="bg-cover w-full h-60">
                                    <img id="preview-image" class="w-full h-60" src="{{ asset('storage/' . $noticia->foto ) }}">
                                </div>

                                <div class="mt-4 flex text-sm leading-6 text-gray-600">
                                    <label for="foto" class="relative cursor-pointer rounded-md bg-white font-semibold text-indigo-600 focus-within:outline-none focus-within:ring-2 focus-within:ring-indigo-600 focus-within:ring-offset-2 hover:text-indigo-500">
                                        <div class="flex flex-col items-center justify-center">
                                            <span>Subir Imagen</span>
                                            <p class="text-xs leading-5 text-gray-600">PNG, JPG, up to 1MB</p>
                                        </div>
                                        <input type="file" id="foto" name="foto" class="sr-only">
                                    </label>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>

                <div class="mt-6 flex justify-center gap-x-6">
                    <button type="submit" class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Guardar</button>
                </div>
            </div>
        </form>
    </div>
</x-app-layout>

<script>
    document.getElementById('foto').addEventListener('change', function(e) {
        var file = e.target.files[0];
        var reader = new FileReader();
        var preview = document.getElementById('preview');
        var previewImage = document.getElementById('preview-image');

        if (file) {
            reader.onloadend = function() {
                previewImage.src = reader.result;
                previewImage.style.display = 'block';
                preview.style.backgroundImage = 'none';
            }
            reader.readAsDataURL(file);
        }
        else {
            previewImage.style.display = 'none';
            preview.style.backgroundImage = 'url("' + previewImage.src + '")';
            preview.style.backgroundSize = 'cover'; // Asegura que la imagen se ajuste al contenedor
        }
    });
</script>

resources/views/back/noticias/index.blade.php
<x-app-layout>
    <div class="m-6">
        <x-alerta/>

        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
            @foreach ($noticias as $noticia)
                <div class="max-w-sm bg-white border border-gray-200 rounded-lg shadow-md dark:bg-gray-800 dark:border-gray-700 overflow-hidden transition-transform duration-500 ease-out hover:scale-105 relative flex flex-col">
                    <div class="absolute top-0 right-0 p-2 bg-white bg-opacity-75 rounded-md">
                        <p class="text-xs text-gray-500">{{ $noticia->created_at->diffForHumans() }}</p>
                    </div>
                    <a href="#">
                        <img class="w-full h-48 object-cover" src="{{ asset('storage/fotos/koala.jpg') }}" alt="" />
                    </a>

                    <div class="p-5 flex-grow">
                        <a href="#">
                            <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">{{ $noticia->titulo }}</h5>
                        </a>
                        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">{{ Str::limit($noticia->contenido, 100, '...') }}</p>
                    </div>
                    <div class="p-5">
                        <div class="flex justify-start items-start space-x-2">
                            <a href="{{ route('back.noticias.show', $noticia) }}" class="inline-flex justify-center items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-500 rounded-lg hover:bg-blue-600 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-400 dark:hover:bg-blue-500 dark:focus:ring-blue-600">
                                Ver más
                            </a>
                        </div>
                    </div>
                </div>

                <x-modalborrado
                    idModal="modalborrado-{{ $noticia->id }}"
                    mensaje="¿Estás seguro de que quieres borrar esta noticia?"
                    ruta="{{ route('back.noticias.destroy', $noticia) }}"
                />
            @endforeach
        </div>
    </div>
</x-app-layout>

resources/views/back/noticias/listado.blade.php
<x-app-layout>
    <div class="m-6">
        <x-alerta/>

        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
            @foreach ($noticias as $noticia)
                <div class="max-w-sm bg-white border border-gray-200 rounded-lg shadow-md dark:bg-gray-800 dark:border-gray-700 overflow-hidden transition-transform duration-500 ease-out hover:scale-105 relative flex flex-col">
                    <div class="absolute top-0 right-0 p-2 bg-white bg-opacity-75 rounded-md">
                        <p class="text-xs text-gray-500">{{ $noticia->created_at->diffForHumans() }}</p>
                    </div>
                    <a href="#">
                        <img class="w-full h-48 object-cover" src="{{ asset('storage/fotos/koala.jpg') }}" alt="" />
                    </a>

                    <div class="p-5 flex-grow">
                        <a href="#">
                            <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">{{ $noticia->titulo }}</h5>
                        </a>
                        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">{{ Str::limit($noticia->contenido, 100, '...') }}</p>
                    </div>
                    <div class="p-5">
                        <div class="flex justify-center items-center space-x-2">
                            <a href="{{ route('back.noticias.show', $noticia) }}" class="inline-flex justify-center items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-500 rounded-lg hover:bg-blue-600 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-400 dark:hover:bg-blue-500 dark:focus:ring-blue-600">
                                Ver más
                            </a>
                            <a href="{{ route('back.noticias.edit', $noticia) }}" class="inline-flex justify-center items-center px-3 py-2 text-sm font-medium text-center text-white bg-green-500 rounded-lg hover:bg-green-600 focus:ring-4 focus:outline-none focus:ring-green-300 dark:bg-green-400 dark:hover:bg-green-500 dark:focus:ring-green-600">
                                Editar
                            </a>
                            <button data-modal-show="modalborrado-{{ $noticia->id }}" class="inline-flex justify-center items-center px-3 py-2 text-sm font-medium text-center text-white bg-red-500 rounded-lg hover:bg-red-600 focus:ring-4 focus:outline-none focus:ring-red-300 dark:bg-red-400 dark:hover:bg-red-500 dark:focus:ring-red-600">
                                Borrar
                            </button>
                        </div>
                    </div>
                </div>

                <x-modalborrado
                    idModal="modalborrado-{{ $noticia->id }}"
                    mensaje="¿Estás seguro de que quieres borrar esta noticia?"
                    ruta="{{ route('back.noticias.destroy', $noticia) }}"
                />
            @endforeach
        </div>
    </div>

    @pushn('js')
        <script>
            document.addEventListener('DOMContentLoaded', () => {
                const showModal = (modalId) => {
                    document.getElementById(modalId).classList.remove('hidden');
                };

                const hideModal = (modalId) => {
                    document.getElementById(modalId).classList.add('hidden');
                };

                document.querySelectorAll('[data-modal-show]').forEach(button => {
                    button.addEventListener('click', () => {
                        showModal(button.getAttribute('data-modal-show'));
                    });
                });

                document.querySelectorAll('[data-modal-hide]').forEach(button => {
                    button.addEventListener('click', () => {
                        hideModal(button.getAttribute('data-modal-hide'));
                    });
                });
            });
        </script>
    @endpushn
</x-app-layout>

resources/views/back/noticias/show.blade.php
<x-app-layout>
    <x-tarjetaback
        :registro="$noticia"
        modelo="noticias"
        titulo='Noticia'
        modalMensaje="¿Estás seguro de que quieres borrar esta noticia?"
    />
</x-app-layout>

@pushn('js')
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const showModal = (modalId) => {
                document.getElementById(modalId).classList.remove('hidden');
            };

            const hideModal = (modalId) => {
                document.getElementById(modalId).classList.add('hidden');
            };

            document.querySelectorAll('[data-modal-show]').forEach(button => {
                button.addEventListener('click', () => {
                    showModal(button.getAttribute('data-modal-show'));
                });
            });

            document.querySelectorAll('[data-modal-hide]').forEach(button => {
                button.addEventListener('click', () => {
                    hideModal(button.getAttribute('data-modal-hide'));
                });
            });
        });
    </script>
@endpushn